console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[transient_prompt]
  template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'p:black'
    background = 'p:yellow'
    type = 'session'

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ path .Path .Location }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:orange'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:white'
    powerline_symbol = ''
    background = '#6CA35E'
    type = 'git'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#fff{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#fff{{ end }}', '{{ if gt .Ahead 0 }}#fff{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#6CA35E{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#6CA35E{{ end }}', '{{ if gt .Ahead 0 }}#6CA35E{{ end }}', '{{ if gt .Behind 0 }}#6CA35E{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    style = 'powerline'
    template = '  '
    foreground = 'p:white'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'root'

  # [[blocks.segments]]
  #   style = 'powerline'
  #   template = ' <p:lightblack><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
  #   foreground = '#3EC669'
  #   powerline_symbol = ''
  #   background = '#29315A'
  #   type = 'time'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Full }}'
    foreground = 'p:green'
    background = 'transparent'
    type = 'node'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = true
      home_enabled = false

  [[blocks.segments]]
    style = 'powerline'
    template = ' ﳑ {{ .Full }} '
    foreground = 'p:white'
    background = 'transparent'
    type = 'go'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .Full }} '
    foreground = '#100e23'
    powerline_symbol = ''
    background = 'yellow'
    type = 'python'

    [blocks.segments.properties]
      display_default = true
      display_mode = 'files'
      fetch_version = true
      fetch_virtual_env = false
      cache_duration = "none"

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .Full }} '
    foreground = '#193549'
    background = '#99908a'
    type = 'rust'

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .Full }} '
    foreground = 'white'
    background = 'blue'
    type = 'lua'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true
      fetch_virtual_env = true

[[tooltips]]
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:white'
  background = 'p:orange'
  type = 'aws'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  tips = ['az']

  [tooltips.properties]
    display_default = true
